name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test_powershell:
    name: WindowsPowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@v4
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      - name: Cache PowerShell modules
        uses: actions/cache@v3
        with:
          path: ~\Documents\WindowsPowerShell\Modules
          key: ${{ runner.os }}-ps-modules-${{ hashFiles('**/requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-ps-modules-
      - name: Install BuildHelpers module
        shell: powershell
        run: |
          Install-Module -Name BuildHelpers -Force -Scope CurrentUser
      - name: Test Bucket
        shell: powershell
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
          
  test_pwsh:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@v4
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      - name: Cache PowerShell Core modules
        uses: actions/cache@v3
        with:
          path: ~\.local\share\powershell\Modules
          key: ${{ runner.os }}-pwsh-modules-${{ hashFiles('**/requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-pwsh-modules-
      - name: Install BuildHelpers module
        shell: pwsh
        run: |
          Install-Module -Name BuildHelpers -Force -Scope CurrentUser
      - name: Test Bucket
        shell: pwsh
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
